Fix bug where --max-results could not be set with --no-context-annotations
Previously this command:

`twarc2 search --archive --max-results 200 --no-context-annotations banana --limit 100`

Would fail with the error:

```
Error: Invalid value for '--max-results': --max-results cannot be greater
than 100 when using context annotations. Set --no-context-annotations to
remove them, or don't specify them in --tweet-fields.
```

This was occuring because _validate_max_results is called before
applying --no-context-annotations, this change just checks
no_context_annotations as well.