Need to import all constants
Otherwise `utils\gender.py --gender unknown tweets.json` doesn't work:
```
Traceback (most recent call last):
  File "M:\twitter\utils\gender.py", line 31, in <module>
    elif options.gender == "unknown" and gender == ANDROGYNOUS:
NameError: name 'ANDROGYNOUS' is not defined
```